- project:
    templates:
      - nodejs4-jobs
      - openstack-python-jobs
      - publish-openstack-sphinx-docs
      - openstack-python35-jobs
    periodic:
      jobs:
        - legacy-periodic-package-stackviz-element
