- project:
    templates:
      - nodejs4-jobs
      - openstack-python-jobs
      - publish-openstack-docs-pti
      - openstack-python35-jobs
      - openstack-python36-jobs
    periodic:
      jobs:
        - legacy-periodic-package-stackviz-element
